Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2023-11, with the labels that each got.

#82 [#81][FEATURE] MDS 적용
  src/assets/icons/IcDate.svg
  src/assets/icons/IcDropdownCheck.svg
  src/assets/icons/IcMore.svg
  src/assets/icons/IcPlace.svg
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/SessionDetailModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/AttendanceChip/index.tsx
  src/components/common/AttendanceChip/style.ts
  src/components/common/Chip/index.tsx
  src/components/common/Chip/style.ts
  src/components/common/FilterButton/index.tsx
  src/components/common/FilterButton/style.ts
  src/components/common/FloatingButton/index.tsx
  src/components/common/FloatingButton/style.ts
  src/components/common/Layout/style.ts
  src/components/common/ListActionButton/style.ts
  src/components/common/ListWrapper/index.tsx
  src/components/common/ListWrapper/style.ts
  src/components/session/Select/index.tsx
  src/components/session/Select/style.ts
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/pages/attendanceAdmin/session/index.tsx
  src/styles/fonts.ts
  src/styles/global.ts
  src/utils/translator.ts
Labels: size/XXL

#84 [#83][REFACTOR] 세션 생성 모달 mds기반으로 변경
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/style.ts
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/common/DropDown/style.ts
  src/components/common/Selector/index.tsx
  src/components/common/Selector/style.ts
  src/styles/global.ts
  src/utils/session.ts
Labels: ⚒️ refactor, size/XL

#86 [#85][REFACTOR] 기수 생성 드롭다운 mds 기반 디자인과 로직으로 변경
  src/assets/icons/SoptLogos/DoSoptLogo.svg
  src/assets/icons/SoptLogos/GoSoptLogo.svg
  src/assets/icons/SoptLogos/index.ts
  src/components/common/Nav/GenerationDropDown/index.tsx
  src/components/common/Nav/GenerationDropDown/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/utils/nav.ts
Labels: ⚒️ refactor, size/L

#87 feat: 알림 관리 리스트 구현
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/AlarmList/style.ts
  src/pages/alarmAdmin/index.tsx
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/alarm/index.ts
  src/services/api/alarm/query.ts
  src/types/global.d.ts
  src/utils/translator.ts
Labels: size/L

#88 [STYLE] 버튼 mds 기반으로 변경
  src/components/common/Button/style.ts
  src/components/common/ListActionButton/style.ts
  src/components/common/modal/ModalFooter/style.ts
Labels: size/S

#89 [FIX] submit 버튼 활성화 문제 해결
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/common/Button/style.ts
Labels: size/S

#90 style : 로그인 화면 mds 기반으로 변경
  src/assets/icons/SoptLogos/SoptMainLogo.svg
  src/assets/icons/SoptLogos/index.ts
  src/components/common/Input/style.ts
  src/components/common/OptionTemplate/style.ts
  src/pages/index.tsx
Labels: size/M

#93 [REFACTOR] 세션 삭제 로직 변경
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
Labels: ⚒️ refactor, size/L

#92 [STYLE]1/2차 출석 모달 mds 형식에 맞춰 변경
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
  src/components/attendanceAdmin/session/AttendanceModal/style.ts
Labels: size/M
