Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2023-04, with the labels that each got.

#6 [#2][FEATURE] 공통_공통 컴포넌트 구현
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
  src/components/common/Footer/index.tsx
  src/components/common/Footer/style.ts
  src/components/common/ListWrapper/index.tsx
  src/components/common/ListWrapper/style.ts
  src/components/common/PartFilter/index.tsx
  src/components/common/PartFilter/style.ts
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/styles/global.ts
  src/utils/index.ts
  src/utils/translator.ts
Labels: ✨ feature, size/XL

#9 [#7}{FEATURE] 공통_공통 컴포넌트(nav, header, modal) 구현
  next.config.js
  package.json
  src/assets/asset.d.ts
  src/assets/icons/IcGoPrev.svg
  src/assets/icons/IcModalClose.svg
  src/assets/icons/IcNavMenu.svg
  src/assets/icons/index.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/components/common/icons/IcDropDown.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  yarn.lock
Labels: ✨ feature, size/XL

#10 [#5][FEATURE] 공통_임시 로그인
  .eslintrc.json
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/Layout/index.tsx
  src/components/common/Loading/index.tsx
  src/components/common/Loading/style.ts
  src/components/common/icons/IcDropDown.tsx
  src/configs/config.ts
  src/hooks/useInput.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/services/api/auth/index.ts
  src/services/api/lecture/index.ts
  src/services/api/user/user.ts
  src/store/globalStore.ts
  src/types/global.d.ts
  src/utils/auth.ts
Labels: ✨ feature, size/L

#18 [#12][FEATURE] 공통_로그인 뷰 퍼블리싱
  src/pages/index.tsx
  src/services/api/auth/index.ts
Labels: ✨ feature, size/L

#16 [#1][FEATURE]출석세션_전체세션리스트, 출석총점 구현
  emotion.d.ts
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/session/SessionListFooter/index.tsx
  src/components/attendanceAdmin/session/SessionListFooter/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/Header/style.ts
  src/components/common/ListWrapper/style.ts
  src/components/common/Nav/index.tsx
  src/components/example/Example.stories.tsx
  src/components/example/Example.tsx
  src/pages/attendanceAdmin/session/index.tsx
  src/pages/attendanceAdmin/totalScore/index.tsx
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/services/api/user/user.ts
  src/styles/theme.ts
  src/types/global.d.ts
  src/utils/nav.ts
  src/utils/session.ts
Labels: ✨ feature, size/L

#17 [#3][FEATURE] 출석세션_세션선택 뷰 구현
  emotion.d.ts
  src/components/common/Footer/style.ts
  src/components/common/Header/style.ts
  src/components/common/ListWrapper/index.tsx
  src/components/common/ListWrapper/style.ts
  src/components/icons/IcDropdown.tsx
  src/components/session/Select/index.tsx
  src/components/session/Select/style.ts
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/pages/attendanceAdmin/session/index.tsx
  src/services/api/attendance/index.ts
  src/services/api/auth/index.ts
  src/services/api/lecture/index.ts
  src/styles/theme.ts
  src/types/global.d.ts
  src/utils/index.ts
  src/utils/translator.ts
  src/utils/zIndex.ts
Labels: ✨ feature, size/XL

#19 fix: login error
  src/services/api/auth/index.ts
Labels: size/XS

#20 fix: precision error
  src/utils/index.ts
Labels: size/XS

#21 Hotfix 230421
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/common/modal/style.ts
  src/utils/zIndex.ts
Labels: 🔥 hotfix, size/S

#26 fix : 디자인 QA - 출석생성 모달 값 유무에 따른 border 색상 변경
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
Labels: 🔥 hotfix, size/S

#27 Hotfix 230425
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/common/DropDown/style.ts
Labels: 🔥 hotfix, size/XS

#28 [#22][FEATURE] 출석세션_출석하기
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
  src/components/attendanceAdmin/session/AttendanceModal/style.ts
  src/components/common/Button/index.tsx
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/lecture/index.ts
  src/types/global.d.ts
Labels: ✨ feature, size/L

#25 [#24] [REFACTOR] PartFilter 의존성 분리
  src/components/common/FilterButton/index.tsx
  src/components/common/FilterButton/style.ts
  src/components/common/PartFilter/index.tsx
Labels: size/M

#23 [FEATURE]공통_react-query 적용 및 QA 수정사항 적용
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/DropDown/style.ts
  src/components/common/Header/style.ts
  src/components/common/Loading/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/types/global.d.ts
  src/utils/auth.ts
  src/utils/nav.ts
Labels: ✨ feature, size/L

#29 Merge dev into main
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
  src/components/attendanceAdmin/session/AttendanceModal/style.ts
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/Button/index.tsx
  src/components/common/DropDown/style.ts
  src/components/common/FilterButton/index.tsx
  src/components/common/FilterButton/style.ts
  src/components/common/Header/style.ts
  src/components/common/Loading/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/components/common/PartFilter/index.tsx
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/types/global.d.ts
  src/utils/auth.ts
  src/utils/nav.ts
  src/utils/session.ts
Labels: size/XL

#30 fix : ios req error
  src/utils/session.ts
Labels: 🔥 hotfix, size/XS

#31 [#4][FEATURE] 출석총점_회원선택 모달 구현
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/attendance/index.ts
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/types/global.d.ts
Labels: ✨ feature, size/L

#32 fix: QA 수정사항 반영
  package.json
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/DropDown/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  src/components/session/Select/style.ts
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
Labels: 🔥 hotfix, size/L

#33 Merge dev into main
  package.json
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/style.ts
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/style.ts
  src/components/common/DropDown/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/style.ts
  src/components/session/Select/style.ts
  src/data/sessionData.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/attendance/index.ts
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/types/global.d.ts
Labels: size/L
