Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2023-09, with the labels that each got.

#57 [#12][FEATURE] 공통_로그인 refresh token 적용
  package.json
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
  src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/hooks/useCreateSession.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/attendance/index.ts
  src/services/api/auth/index.ts
  src/services/api/client.ts
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/types/global.d.ts
  src/utils/auth.ts
Labels: size/L

#59 chore : recoil atom default 값 변경
  src/recoil/atom.ts
Labels: size/XS

#60 fix : 드롭다운 위치 수정
  src/components/common/DropDown/style.ts
Labels: size/XS

#64 [#63}[REFACTOR] createSession 날짜 포맷 ISO 8601 형식으로 변경
  src/components/attendanceAdmin/session/CreateSessionModal/index.tsx
Labels: ⚒️ refactor, size/S

#65 refactor : 드롭다운 외부 클릭 시 닫힘
  src/components/common/Nav/index.tsx
Labels: size/S

#67 [#13][FEATURE] 공통_react query + 무한스크롤 적용
  src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/data/queryData.ts
  src/hooks/useObserver.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/services/api/attendance/index.ts
  src/services/api/attendance/query.ts
  src/services/api/lecture/index.ts
  src/services/api/lecture/query.ts
  src/services/api/member/index.ts
  src/services/api/member/query.ts
  src/utils/index.ts
Labels: size/XL

#68 [#66][REFACTOR] 보라색 걷어내기 sprint0 ver.
  src/components/attendanceAdmin/session/CreateSessionModal/style.ts
  src/components/orgAdmin/TextField/style.ts
Labels: ⚒️ refactor, size/XS

#69 style : 디자인 QA 사항 (1, 2, 3, 7) 반영
  src/assets/icons/IcCheckBox.tsx
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/attendanceAdmin/totalScore/MemberDetail/index.tsx
  src/components/attendanceAdmin/totalScore/MemberDetail/style.ts
  src/components/common/ListWrapper/style.ts
Labels: size/M
