Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2023-10, with the labels that each got.

#73 fix : 리프레시 토큰 요청에 대한 400 에러 리디렉션
  src/services/api/auth/index.ts
  src/services/api/client.ts
Labels: size/S

#71 [#70][REFACTOR] 이전 기수에 대한 세션 생성/출석 기능 제한
  package.json
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/session/SessionListFooter/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/components/common/ListActionButton/index.tsx
  src/components/common/ListActionButton/style.ts
  src/components/common/ListWrapper/style.ts
  src/components/common/Nav/index.tsx
  src/components/session/Select/index.tsx
  src/hooks/useRecoilGenerationSSR.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/recoil/atom.ts
  yarn.lock
Labels: size/L

#74 [FEATURE] helper text 추가
  emotion.d.ts
  src/components/common/HelperText/index.tsx
  src/components/common/HelperText/style.ts
  src/hooks/useObserver.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/styles/theme.ts
  src/utils/zIndex.ts
Labels: size/L

#77 fix: setInterval 오류 수정 및 조기종료 추가
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
Labels: size/M

#76 [#75][REFACTOR] 출석 관련 로직 비활성화, 서버측 데이터로 제어
  src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx
  src/components/attendanceAdmin/session/SessionListFooter/index.tsx
  src/components/common/Nav/index.tsx
  src/components/session/Select/index.tsx
  src/hooks/useRecoilGenerationSSR.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/utils/date.ts
  src/utils/generation.ts
Labels: size/M

#78 [231026] dev -> main merge
  package.json
  src/components/attendanceAdmin/session/AttendanceModal/index.tsx
  src/components/attendanceAdmin/session/SessionList/SessionDetailModal/index.tsx
  src/components/attendanceAdmin/session/SessionListFooter/index.tsx
  src/components/common/Nav/index.tsx
  src/components/session/Select/index.tsx
  src/hooks/useRecoilGenerationSSR.ts
  src/pages/attendanceAdmin/session/[id].tsx
  src/styles/global.ts
  src/utils/date.ts
  src/utils/generation.ts
  yarn.lock
Labels: size/L

#79 [STYLE] nav, header mds 기반의 디자인으로 변경
  src/assets/icons/IcAlarmMenu.svg
  src/assets/icons/IcAttendanceMenu.svg
  src/assets/icons/IcNavMenu.svg
  src/assets/icons/IcOrgMenu.svg
  src/assets/icons/index.ts
  src/components/common/Header/index.tsx
  src/components/common/Header/style.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/pages/alarmAdmin/index.tsx
  src/utils/nav.ts
Labels: size/L

#80 Feat create alarm
  src/assets/icons/IcDeleteFile.svg
  src/assets/icons/IcModalClose.svg
  src/assets/icons/IcNewDropdown.svg
  src/assets/icons/IcUpload.svg
  src/assets/icons/index.ts
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/style.ts
  src/components/common/DropDown/style.ts
  src/components/common/Input/index.tsx
  src/components/common/Input/style.ts
  src/components/common/OptionTemplate/index.tsx
  src/components/common/OptionTemplate/style.ts
  src/components/common/modal/ModalFooter/index.tsx
  src/components/common/modal/ModalFooter/style.ts
  src/components/common/modal/ModalHeader/index.tsx
  src/components/common/modal/ModalHeader/style.ts
  src/components/common/modal/style.ts
  src/pages/alarmAdmin/index.tsx
  src/services/api/alarm/index.ts
  src/types/global.d.ts
  src/utils/alarm.ts
Labels: size/XL
