Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2023-05, with the labels that each got.

#37 feat : 30분 단위 시간 추가
  src/utils/session.ts
Labels: 🔥 hotfix, size/XS

#36 [#35][Feature] Feature sopt org admin
  .gitignore
  next.config.js
  src/components/orgAdmin/AboutTab/AboutTabAction/index.tsx
  src/components/orgAdmin/AboutTab/AboutTabAction/style.ts
  src/components/orgAdmin/AboutTab/AboutTabManagement/CoreValueInput/index.tsx
  src/components/orgAdmin/AboutTab/AboutTabManagement/CoreValueInput/style.ts
  src/components/orgAdmin/AboutTab/AboutTabManagement/index.tsx
  src/components/orgAdmin/AboutTab/AboutTabManagement/style.ts
  src/components/orgAdmin/AboutTab/index.tsx
  src/components/orgAdmin/AboutTab/style.ts
  src/components/orgAdmin/ImageSelect/index.tsx
  src/components/orgAdmin/ImageSelect/style.ts
  src/components/orgAdmin/PartFilter/index.tsx
  src/components/orgAdmin/SnackBar/index.tsx
  src/components/orgAdmin/SnackBar/style.ts
  src/components/orgAdmin/TextField/index.tsx
  src/components/orgAdmin/TextField/style.ts
  src/configs/config.ts
  src/pages/orgAdmin/aboutTabManagement/index.tsx
  src/services/api/aboutSopt/index.ts
  src/services/api/client.ts
  src/types/global.d.ts
  src/utils/auth.ts
  src/utils/nav.ts
  src/utils/putObject.ts
Labels: ✨ feature, size/XXL

#38 fix : 403 에러 처리(전체세션리스트, 멤버리스트)
  src/components/attendanceAdmin/session/SessionList/index.tsx
  src/components/attendanceAdmin/totalScore/MemberList/index.tsx
  src/services/api/auth/index.ts
  src/services/api/client.ts
  src/services/api/lecture/index.ts
  src/services/api/member/index.ts
  src/services/api/user/user.ts
  src/utils/auth.ts
Labels: 🔥 hotfix, size/L
