Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2024-12, with the labels that each got.

#164 [FEATURE] 공통 Modal 구현 및 적용, 홈 & 소개 탭 UI 수정사항 반영
  public/images/org/imgAboutHeaderInfo.png
  public/images/org/imgLatestNewsInfo.png
  public/images/org/imgPartInfo.png
  public/images/org/imgRecruitHeaderInfo.png
  public/images/org/imgSubColorInfo.png
  src/components/org/OrgAdmin/AboutSection/CoreValue/index.tsx
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
  src/components/org/OrgAdmin/AboutSection/HeaderBanner/index.tsx
  src/components/org/OrgAdmin/AboutSection/HeaderBanner/style.ts
  src/components/org/OrgAdmin/AboutSection/style.ts
  src/components/org/OrgAdmin/CommonSection/BrandingColor.tsx
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/components/org/OrgAdmin/HomeSection/ButtonSection.tsx
  src/components/org/OrgAdmin/HomeSection/HomeSection.tsx
  src/components/org/OrgAdmin/HomeSection/ImageInput.tsx
  src/components/org/OrgAdmin/HomeSection/LiveAppliedButton.tsx
  src/components/org/OrgAdmin/HomeSection/Modal.style.ts
  src/components/org/OrgAdmin/HomeSection/Modal.tsx
  src/components/org/OrgAdmin/HomeSection/NewsItem.tsx
  src/components/org/OrgAdmin/HomeSection/NewsSection.tsx
  src/components/org/OrgAdmin/HomeSection/PartIntroSection.tsx
  src/components/org/OrgAdmin/HomeSection/SampleView.tsx
  src/components/org/OrgAdmin/HomeSection/api.ts
  src/components/org/OrgAdmin/HomeSection/constant.ts
  src/components/org/OrgAdmin/HomeSection/queries.ts
  src/components/org/OrgAdmin/HomeSection/style.ts
  src/components/org/OrgAdmin/RecruitSection/Header.tsx
  src/components/org/OrgAdmin/RecruitSection/style.ts
  src/components/org/OrgAdmin/common/Modal/index.tsx
  src/components/org/OrgAdmin/common/Modal/style.ts
  src/components/org/OrgAdmin/common/Modal/useModal.ts
  src/components/org/OrgAdmin/home/HomeSection.tsx
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/style.ts
Labels: size/XL

#165 [BUG] openAPI spec type 에러 해결
  package.json
  src/__generated__/org-admin.json
  src/__generated__/org-types/Admin.ts
  src/__generated__/org-types/Health.ts
  src/__generated__/org-types/Homepage.ts
  src/__generated__/org-types/Notification.ts
  src/__generated__/org-types/Projects.ts
  src/__generated__/org-types/Semesters.ts
  src/__generated__/org-types/data-contracts.ts
  src/__generated__/org-types/http-client.ts
  src/components/org/OrgAdmin/api.ts
  src/components/org/OrgAdmin/hooks.ts
  src/components/org/OrgAdmin/index.tsx
  yarn.lock
Labels: size/L

#168 [FEATURE] generated 된 파일 pr에 숨김 처리하기
  .gitattributes
  package.json
  src/__generated__/api.d.ts
  src/__generated__/org-types/Notification.ts
  src/__generated__/org-types/Projects.ts
  src/__generated__/org-types/data-contracts.ts
Labels: size/XS

#175 [FIX] layout main 태그가 자식 요소에 중첩되는 문제 해결
  src/components/common/Layout/style.ts
Labels: size/XS

#187 [BUG] 폰트가 두껍게 보이는 오류 해결 및 폰트 수정
  src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
  src/components/org/OrgAdmin/AboutSection/style.ts
  src/styles/global.ts
Labels: size/S

#181 [BUG] 소개 탭 파트별 커리큘럼 label 미스 매치
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
Labels: size/XS

#185 [BUG] 공통 탭 서브 컬러 input들 정렬 맞추고 컬러 코드에 # 제거하기
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/components/org/OrgAdmin/CommonSection/utils.ts
Labels: size/M

#179 [FEATURE] org admin 빈 곳 있을 시 해당 섹션으로 이동
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/index.tsx
  src/components/org/OrgAdmin/AboutSection/index.tsx
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/utils.ts
  src/pages/org/org-admin/index.tsx
  src/utils/org.ts
Labels: size/XL

#183 [FEATURE] 에러 상태 빠진 곳 UI 구현
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
  src/components/org/OrgAdmin/MyDropzone/index.tsx
Labels: size/S
