Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2024-11, with the labels that each got.

#115 [FEATURE] 알림 발송 Modal 구현
  .pnp.cjs
  .yarn/install-state.gz
  package.json
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/DatePickerSelect.tsx
  src/components/alarmAdmin/CreateAlarmModal/LabeledComponent.tsx
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/style.ts
  src/components/alarmAdmin/CreateAlarmModal/type.ts
  src/components/alarmAdmin/CreateAlarmModal/utils.ts
  src/components/common/modal/ModalFooter/style.ts
  src/components/common/modal/ModalHeader/style.ts
  src/pages/alarmAdmin/index.tsx
  src/services/api/alarm/index.ts
  src/types/global.d.ts
  yarn.lock
Labels: size/XXL

#123 [FEATURE] 공홈 어드민 공통 페이지 퍼블리싱
  .pnp.cjs
  .yarn/install-state.gz
  package.json
  public/images/.keep
  public/images/org/imgSubColorInfo.png
  src/components/common/Button/style.ts
  src/components/common/FilterButton/index.tsx
  src/components/common/Form/style.ts
  src/components/common/inputContainer/style.ts
  src/components/org/OrgAdmin/CommonSection/BrandingColor.tsx
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
  src/components/org/OrgAdmin/CommonSection/GenerationInformation.tsx
  src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
  src/components/org/OrgAdmin/CommonSection/index.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/components/org/OrgAdmin/CommonSection/utils.ts
  src/components/org/OrgAdmin/assets/SubmitIcon.tsx
  src/components/org/OrgAdmin/assets/imgSubColorInfo.png
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/style.ts
  src/pages/index.tsx
  src/utils/org.ts
  src/utils/putObject.ts
  yarn.lock
Labels: size/XL

#130 [FEATURE] 공홈 어드민 지원하기 페이지 퍼블리싱
  .pnp.cjs
  .yarn/install-state.gz
  package.json
  src/components/org/OrgAdmin/CommonSection/BrandingColor.tsx
  src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
  src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/components/org/OrgAdmin/MyDropzone/index.tsx
  src/components/org/OrgAdmin/MyDropzone/style.ts
  src/components/org/OrgAdmin/PartCategory/index.tsx
  src/components/org/OrgAdmin/PartCategory/style.ts
  src/components/org/OrgAdmin/RecruitSection/Fna.tsx
  src/components/org/OrgAdmin/RecruitSection/Header.tsx
  src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
  src/components/org/OrgAdmin/RecruitSection/index.tsx
  src/components/org/OrgAdmin/RecruitSection/style.ts
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/style.ts
  src/utils/org.ts
  yarn.lock
Labels: size/XL

#134 [FEATURE] api type 생성
  .pnp.cjs
  .yarn/install-state.gz
  package.json
  src/__generated__/api.ts
  src/__generated__/org-admin.json
  src/components/org/api.ts
  yarn.lock
Labels: size/L

#136 [FEATURE] 공통 컴포넌트 MyDropZone, PartCategory 확장
  .pnp.cjs
  .yarn/install-state.gz
  src/components/org/OrgAdmin/AboutSection/CoreValue/index.tsx
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/SNSInput.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/style.ts
  src/components/org/OrgAdmin/AboutSection/HeaderBanner/index.tsx
  src/components/org/OrgAdmin/AboutSection/HeaderBanner/style.ts
  src/components/org/OrgAdmin/AboutSection/style.ts
  src/components/org/OrgAdmin/MyDropzone/index.tsx
  src/components/org/OrgAdmin/MyDropzone/style.ts
  src/components/org/OrgAdmin/PartCategory/index.tsx
  src/components/org/OrgAdmin/RecruitSection/Fna.tsx
  src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
  src/components/org/OrgAdmin/index.tsx
Labels: size/L

#128 [FEATURE] 공홈 어드민 홈 페이지 퍼블리싱
  .pnp.cjs
  .yarn/install-state.gz
  next.config.js
  src/assets/img/latestNewsSample.png
  src/assets/img/partIntroduceSample.png
  src/components/common/Layout/style.ts
  src/components/org/OrgAdmin/home/ButtonSection.tsx
  src/components/org/OrgAdmin/home/HomeSection.tsx
  src/components/org/OrgAdmin/home/ImageInput.tsx
  src/components/org/OrgAdmin/home/LiveAppliedButton.tsx
  src/components/org/OrgAdmin/home/Modal.style.ts
  src/components/org/OrgAdmin/home/Modal.tsx
  src/components/org/OrgAdmin/home/NewsItem.tsx
  src/components/org/OrgAdmin/home/NewsSection.tsx
  src/components/org/OrgAdmin/home/PartIntroSection.tsx
  src/components/org/OrgAdmin/home/SampleView.tsx
  src/components/org/OrgAdmin/home/constant.ts
  src/components/org/OrgAdmin/home/style.ts
  src/components/org/OrgAdmin/index.tsx
  src/hooks/useBooleanState.ts
  yarn.lock
Labels: ✨ feature, size/XL

#143 [FEATURE] 공통 탭 UI 수정
  .pnp.cjs
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
  src/components/org/OrgAdmin/CommonSection/GenerationInformation.tsx
  src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
Labels: size/L

#148 [FEATURE] 소개탭, 지원하기탭 필수조건 에러처리 및 label 수정
  src/components/org/OrgAdmin/AboutSection/CoreValue/index.tsx
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
  src/components/org/OrgAdmin/RecruitSection/Fna.tsx
  src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
Labels: size/L

#149 [FEAUTRE] 공홈 어드민 공통 탭 hook form 연결
  src/components/org/OrgAdmin/CommonSection/BrandingColor.tsx
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/ColorInputField.tsx
  src/components/org/OrgAdmin/CommonSection/GenerationInformation.tsx
  src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/utils/org.ts
Labels: size/L

#145 [FEATURE] 지원하기 탭 UI 수정
  src/components/org/OrgAdmin/RecruitSection/Fna.tsx
  src/components/org/OrgAdmin/RecruitSection/Header.tsx
  src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
  src/components/org/OrgAdmin/RecruitSection/style.ts
  src/components/org/OrgAdmin/assets/RequiredIcon.tsx
Labels: size/M

#150 [BUG] dropzone 클릭으로도 파일 입력가능하게 하기
  src/components/org/OrgAdmin/MyDropzone/index.tsx
Labels: size/XS

#152 [FEATURE] api instance 수정 및 자동화
  package.json
  src/__generated__/api.d.ts
  src/__generated__/org-admin.json
Labels: size/XS

#154 [FEATURE] 공통 탭 hook-form 고도화
  src/components/org/OrgAdmin/CommonSection/BrandingSubColor.tsx
  src/components/org/OrgAdmin/CommonSection/RecruitSchedule.tsx
  src/components/org/OrgAdmin/CommonSection/index.tsx
  src/components/org/OrgAdmin/CommonSection/style.ts
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/types.ts
  src/utils/org.ts
Labels: size/L

#156 [FEATURE] 지원하기 탭 hook-form 고도화
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/PartCategory/index.tsx
  src/components/org/OrgAdmin/RecruitSection/Fna.tsx
  src/components/org/OrgAdmin/RecruitSection/PartCurriculum.tsx
  src/components/org/OrgAdmin/RecruitSection/index.tsx
  src/components/org/OrgAdmin/index.tsx
  src/utils/org.ts
Labels: size/L

#126 [FEATURE] 알림 리스트 & 상세 조회
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/AlarmList/style.ts
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
  src/components/alarmAdmin/ShowAlarmModal/style.ts
  src/components/common/Header/style.ts
  src/components/common/Nav/style.ts
  src/components/common/modal/ModalHeader/style.ts
  src/pages/alarmAdmin/index.tsx
  src/services/api/alarm/index.ts
  src/services/api/alarm/query.ts
  src/types/global.d.ts
  src/utils/alarm.ts
  src/utils/translator.ts
Labels: size/L

#140 [FEATURE] HOME 탭 hook form 작업 및 API 연결
  package.json
  src/__generated__/org-admin.json
  src/components/org/OrgAdmin/home/ButtonSection.tsx
  src/components/org/OrgAdmin/home/HomeSection.tsx
  src/components/org/OrgAdmin/home/ImageInput.tsx
  src/components/org/OrgAdmin/home/LiveAppliedButton.tsx
  src/components/org/OrgAdmin/home/Modal.style.ts
  src/components/org/OrgAdmin/home/Modal.tsx
  src/components/org/OrgAdmin/home/NewsSection.tsx
  src/components/org/OrgAdmin/home/PartIntroSection.tsx
  src/components/org/OrgAdmin/home/api.ts
  src/components/org/OrgAdmin/home/constant.ts
  src/components/org/OrgAdmin/home/queries.ts
  src/components/org/OrgAdmin/home/style.ts
  src/components/org/api.ts
Labels: ✨ feature, size/L

#158 Feat: Chip에 disabled 추가
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  package.json
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
  yarn.lock
Labels: size/S

#159 [FEATURE] Alarm Admin Base Branch
  .gitignore
  .pnp.cjs
  .pnp.loader.mjs
  package.json
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/AlarmList/style.ts
  src/components/alarmAdmin/CreateAlarmModal/DatePickerSelect.tsx
  src/components/alarmAdmin/CreateAlarmModal/LabeledComponent.tsx
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/style.ts
  src/components/alarmAdmin/CreateAlarmModal/type.ts
  src/components/alarmAdmin/CreateAlarmModal/utils.ts
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
  src/components/alarmAdmin/ShowAlarmModal/style.ts
  src/components/common/Header/style.ts
  src/components/common/Nav/style.ts
  src/components/common/modal/ModalFooter/style.ts
  src/components/common/modal/ModalHeader/style.ts
  src/pages/alarmAdmin/index.tsx
  src/services/api/alarm/index.ts
  src/services/api/alarm/query.ts
  src/types/global.d.ts
  src/utils/alarm.ts
  src/utils/translator.ts
  yarn.lock
Labels: size/XXL

#160 [FEATURE] 배포 API 붙이기
  src/__generated__/api.d.ts
  src/components/org/OrgAdmin/AboutSection/CoreValue/index.tsx
  src/components/org/OrgAdmin/AboutSection/Curriculum/index.tsx
  src/components/org/OrgAdmin/AboutSection/Executives/ExecInfo.tsx
  src/components/org/OrgAdmin/MyDropzone/index.tsx
  src/components/org/OrgAdmin/RecruitSection/Header.tsx
  src/components/org/OrgAdmin/api.ts
  src/components/org/OrgAdmin/home/api.ts
  src/components/org/OrgAdmin/hooks.ts
  src/components/org/OrgAdmin/index.tsx
  src/components/org/api.ts
Labels: size/XL
