Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2025-01, with the labels that each got.

#189 [FEATURE] org admin 배포 연결
  src/components/org/OrgAdmin/api.ts
  src/components/org/OrgAdmin/index.tsx
Labels: size/L

#188 [FEATURE] 홈 탭 - 파트별 소개 validation
  src/components/org/OrgAdmin/index.tsx
  src/components/org/OrgAdmin/utils.ts
Labels: size/M

#191 [BUG] 공홈 어드민 이미지 등록 했다 다른 탭 이동하면 해당 이미지 없어지는 에러 해결
  src/components/org/OrgAdmin/MyDropzone/index.tsx
Labels: size/S

#193 [FEATURE] 공홈 어드민 배포 전 모달 띄우고 성공 시 성공 alert 띄우기
  src/components/org/OrgAdmin/HomeSection/Modal.style.ts
  src/components/org/OrgAdmin/HomeSection/Modal.tsx
  src/components/org/OrgAdmin/HomeSection/NewsSection.tsx
  src/components/org/OrgAdmin/common/ActionModal/index.tsx
  src/components/org/OrgAdmin/common/ActionModal/style.ts
  src/components/org/OrgAdmin/hooks.ts
  src/components/org/OrgAdmin/index.tsx
Labels: size/L

#194 [CHORE] text style 변경
  src/components/org/OrgAdmin/CommonSection/style.ts
Labels: size/XS

#198 [FIX] 최신소식 추가/삭제 에러 해결
  src/components/org/OrgAdmin/HomeSection/api.ts
Labels: 🐛 bug, size/XS

#197 [FEAT] 공홈 어드민 QA용 매직버튼 만들었어요
  src/components/attendanceAdmin/session/SessionList/style.ts
  src/components/org/OrgAdmin/hooks.ts
  src/components/org/OrgAdmin/index.tsx
Labels: size/L
