Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2025-04, with the labels that each got.

#209 [#203] 배너 생성 모달 뷰 구현
  package.json
  src/assets/icons/calendar_big.svg
  src/components/bannerAdmin/BannerImageRegister.tsx
  src/components/bannerAdmin/ContentTypeField.tsx
  src/components/bannerAdmin/CreateBannerModal.tsx
  src/components/bannerAdmin/DateRangeField.tsx
  src/components/bannerAdmin/ImageDropZone.tsx
  src/components/bannerAdmin/LinkField.tsx
  src/components/bannerAdmin/LocationField.tsx
  src/components/bannerAdmin/PublisherField.tsx
  src/components/bannerAdmin/form/Calendar/index.tsx
  src/components/bannerAdmin/form/ErrorMessage/index.tsx
  src/components/bannerAdmin/form/FormController/index.tsx
  src/components/bannerAdmin/form/HelpMessage/index.tsx
  src/components/bannerAdmin/types/form.ts
  src/components/common/modal/ModalHeader/index.tsx
  src/pages/bannerAdmin/index.tsx
  src/styles/global.ts
  yarn.lock
Labels: ✨ feature, size/XXL

#212 [FEATURE] 배너 생성, 삭제, 수정 api 연결
  src/components/alarmAdmin/ShowAlarmModal/style.ts
  src/components/bannerAdmin/BannerEditButton.tsx
  src/components/bannerAdmin/BannerImageRegister.tsx
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/ContentTypeField.tsx
  src/components/bannerAdmin/CreateBannerModal.tsx
  src/components/bannerAdmin/DeleteBannerButton.tsx
  src/components/bannerAdmin/Header/Header.tsx
  src/components/bannerAdmin/ImageDropZone.tsx
  src/components/bannerAdmin/LocationField.tsx
  src/components/bannerAdmin/types/api.ts
  src/components/bannerAdmin/types/form.ts
  src/components/bannerAdmin/utils/converUrlToFile.ts
  src/components/bannerAdmin/utils/getImageSize.ts
  src/components/common/Nav/style.ts
  src/components/common/modal/ModalHeader/index.tsx
  src/components/common/modal/ModalHeader/style.ts
  src/components/org/OrgAdmin/index.tsx
  src/pages/_app.tsx
  src/pages/bannerAdmin/index.tsx
  src/services/api/banner/index.ts
  src/services/api/banner/query.ts
  src/utils/index.ts
Labels: ✨ feature, size/XL

#213 [FEATURE] 배너어드민 탭 메뉴 구현 및 api 연결
  package.json
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/CountTag/CountTag.tsx
  src/constants/index.ts
  src/pages/bannerAdmin/index.tsx
  src/services/api/banner/index.ts
  src/services/api/banner/query.ts
  src/types/global.d.ts
  src/utils/alarm.ts
  src/utils/index.ts
  src/utils/translator.tsx
  yarn.lock
Labels: ✨ feature, size/L

#216 [FIX] 배너어드민 진행완료 배너 수정 및 삭제 비활성화
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/Header/Header.tsx
  src/pages/bannerAdmin/index.tsx
Labels: 🐛 bug, size/M

#218 [REFACTOR] banner 생성 모달 qa (데이트피커 부분 제외)
  src/components/bannerAdmin/BannerImageRegister.tsx
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/ContentTypeField.tsx
  src/components/bannerAdmin/CreateBannerModal.tsx
  src/components/bannerAdmin/DeleteBannerButton.tsx
  src/components/bannerAdmin/ImageDropZone.tsx
  src/components/bannerAdmin/LocationField.tsx
  src/components/bannerAdmin/PublisherField.tsx
  src/components/bannerAdmin/form/Calendar/index.tsx
  src/components/bannerAdmin/types/api.ts
  src/components/bannerAdmin/types/form.ts
  src/components/bannerAdmin/utils/getBannerStatus.ts
  src/components/bannerAdmin/utils/getBannerType.ts
  src/components/common/modal/ModalHeader/index.tsx
  src/hooks/useObserver.ts
  src/pages/_app.tsx
  src/pages/bannerAdmin/index.tsx
  src/pages/index.tsx
  src/services/api/banner/index.ts
  src/services/api/banner/query.ts
  src/utils/index.ts
  src/utils/translator.tsx
Labels: ⚒️ refactor, size/L

#219 [FEATURE] 배너 어드민 리스트 페이지네이션 적용
  src/assets/icons/IcPaginationLeft.svg
  src/assets/icons/IcPaginationRight.svg
  src/assets/icons/index.ts
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/types/api.ts
  src/constants/index.ts
  src/pages/bannerAdmin/index.tsx
  src/services/api/banner/index.ts
  src/services/api/banner/query.ts
  src/utils/translator.tsx
Labels: ✨ feature, size/L

#223 PROD 배포
  package.json
  src/assets/icons/IcBannerMenu.svg
  src/assets/icons/IcEdit.svg
  src/assets/icons/IcPaginationLeft.svg
  src/assets/icons/IcPaginationRight.svg
  src/assets/icons/IcTrash.svg
  src/assets/icons/calendar_big.svg
  src/assets/icons/index.ts
  src/components/alarmAdmin/ShowAlarmModal/style.ts
  src/components/bannerAdmin/BannerEditButton.tsx
  src/components/bannerAdmin/BannerImageRegister.tsx
  src/components/bannerAdmin/BannerList/BannerList.tsx
  src/components/bannerAdmin/BannerTag/BannerTag.tsx
  src/components/bannerAdmin/ContentTypeField.tsx
  src/components/bannerAdmin/CountTag/CountTag.tsx
  src/components/bannerAdmin/CreateBannerModal.tsx
  src/components/bannerAdmin/DateRangeField.tsx
  src/components/bannerAdmin/DeleteBannerButton.tsx
  src/components/bannerAdmin/Header/Header.tsx
  src/components/bannerAdmin/ImageDropZone.tsx
  src/components/bannerAdmin/LinkField.tsx
  src/components/bannerAdmin/LocationField.tsx
  src/components/bannerAdmin/PublisherField.tsx
  src/components/bannerAdmin/form/Calendar/index.tsx
  src/components/bannerAdmin/form/ErrorMessage/index.tsx
  src/components/bannerAdmin/form/FormController/index.tsx
  src/components/bannerAdmin/form/HelpMessage/index.tsx
  src/components/bannerAdmin/types/api.ts
  src/components/bannerAdmin/types/form.ts
  src/components/bannerAdmin/utils/converUrlToFile.ts
  src/components/bannerAdmin/utils/getBannerStatus.ts
  src/components/bannerAdmin/utils/getBannerType.ts
  src/components/bannerAdmin/utils/getImageSize.ts
  src/components/common/Nav/style.ts
  src/components/common/modal/ModalHeader/index.tsx
  src/components/common/modal/ModalHeader/style.ts
  src/components/org/OrgAdmin/index.tsx
  src/constants/index.ts
  src/hooks/useObserver.ts
  src/pages/_app.tsx
  src/pages/bannerAdmin/index.tsx
  src/pages/index.tsx
  src/services/api/banner/index.ts
  src/services/api/banner/query.ts
  src/styles/global.ts
  src/types/global.d.ts
  src/utils/alarm.ts
  src/utils/index.ts
  src/utils/nav.ts
  src/utils/translator.tsx
  yarn.lock
Labels: size/XXL
