Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2025-07, with the labels that each got.

#239 main 배포
  src/components/bannerAdmin/types/form.ts
Labels: size/XS

#241 main 배포
  src/components/bannerAdmin/types/form.ts
Labels: size/XS

#243 Prod 배포
  src/assets/icons/IcApplicationMenu.svg
  src/assets/icons/IcArrowUpRight.svg
  src/assets/icons/index.ts
  src/components/common/Nav/index.tsx
  src/components/common/Nav/style.ts
  src/utils/nav.ts
Labels: size/S

#244 [Feat] 메이커스 어드민 지원서 관리 메뉴 추가
  src/components/common/Nav/index.tsx
Labels: ✨ feature, size/XS

#245 Prod 배포
  src/components/common/Nav/index.tsx
Labels: size/XS

#247 Prod 배포
  src/utils/nav.ts
Labels: size/XS

#250 Prod 배포
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
Labels: size/XS
