Repository sopt-makers/sopt-operation-frontend, pull requests merged in 2025-05, with the labels that each got.

#225 [Feat] 배너 어드민 권한 추가
  src/components/common/Nav/index.tsx
Labels: size/XS

#228 [FEATURE] 권한에 따른 라우팅 분리
  src/components/common/Header/index.tsx
  src/pages/index.tsx
Labels: size/XS

#229 Prod 배포
  src/components/common/Header/index.tsx
  src/pages/index.tsx
Labels: size/XS

#231 [FIX] 메이커스 계정 리다이렉트 url 수정
  src/pages/index.tsx
Labels: 🔥 hotfix, size/XS

#232 PROD 배포
  src/pages/index.tsx
Labels: size/XS

#233 [알림 어드민] high priority QA 사항 해결
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/type.ts
  src/components/alarmAdmin/CreateAlarmModal/utils.ts
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
  src/services/api/alarm/index.ts
  src/types/global.d.ts
Labels: size/L

#234 [알림 어드민] 필드명 오타 수정 및 알림 리스트 아이템 시간 intentAt 으로 수정
  src/components/alarmAdmin/AlarmList/index.tsx
  src/types/global.d.ts
Labels: size/XS

#235 Prod 배포
  src/components/alarmAdmin/AlarmList/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/index.tsx
  src/components/alarmAdmin/CreateAlarmModal/type.ts
  src/components/alarmAdmin/CreateAlarmModal/utils.ts
  src/components/alarmAdmin/ShowAlarmModal/index.tsx
  src/services/api/alarm/index.ts
  src/types/global.d.ts
Labels: size/L
